In [20]:
# Imports
import numpy as np
from itertools import islice
import math

In [21]:
# Creating and exploring a NumPy array
ls = [[x, x + 1, x + 2, x + 3, x + 4] for x in range(1, 30, 5)]
arr = np.array(ls)
print("Full Array:")
print(arr)

Full Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [ ]:
# Accessing array slices
part1 = arr[2:4, 0:2]
part2 = arr[[0, 1, 2, 3], [1, 2, 3, 4]]
part3 = arr[[0, 3, 4], 3:]

print("\narr[2:4, 0:2] -> Rows 2 & 3, Columns 0 & 1:")
print(part1)

print("\narr[[0,1,2,3], [1,2,3,4]] -> Diagonal-like element selection:")
print(part2)

print("\narr[[0,4,5], 3:] -> Rows 0, 4, and 5 with columns 3 to end:")
print(part3)

print("\nRest of the unmarked selections:")
combined = np.concatenate([np.ravel(x) for x in [part1, part2, part3]])
rest = [x for x in np.ravel(arr) if x not in combined]
print(np.array(rest))


arr[2:4, 0:2] -> Rows 2 & 3, Columns 0 & 1:
[[11 12]
 [16 17]]

arr[[0,1,2,3], [1,2,3,4]] -> Diagonal-like element selection:
[ 2  8 14 20]

arr[[0,4,5], 3:] -> Rows 0, 4, and 5 with columns 3 to end:
[[ 4  5]
 [19 20]
 [24 25]]

Rest of the unmarked selections:
[ 1  3  6  7  9 10 13 15 18 21 22 23 26 27 28 29 30]


In [ ]:
# Prime Number Function
def is_prime(num):
    
    # check odd or even:
    if num < 2:
        return False
    if num == 2:
        return True
    if num % 2 == 0:
        return False
    
    # check for odd (not even) factors from 3 to sqrt(num):
    limit = int(math.sqrt(num)) + 1
    for div in range(3, limit, 2):
        if num % div == 0:
            return False
    return True

In [24]:
# Finding primes (inefficient way – tests all numbers up to 999) but uses list comprehension:
ls_all = [x for x in range(1000) if is_prime(x)][:50]
print("First 50 primes (computed by checking all up to 1000):")
print(ls_all)

First 50 primes (computed by checking all up to 1000):
[2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199, 211, 223, 227, 229]
